enabled: true

exclude:
  - "**/*.patch"
  - "**/node_modules/**/*"
  - "**/vendor/**/*"
  - ".github/workflows/**/*"

changed_paths:
  maximum: 1000
  outcome: error

remote_files: []

auto: false

pull_requests: true

comments: false

statuses:
  differences: true
  no_differences: true
  error: true

request_review: author

labels: []

ignore_labels:
  - restyled-ignore

restylers_version: "20200615"

restylers:
  - "*"